name: EMS Downloader Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manuel tetikleme sağlar

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter requests yt-dlp libtorrent-bin pillow cryptography pyinstaller

      - name: Build Portable EXE
        run: |
          # --collect-all: kütüphanelerin gizli bağımlılıklarını paketler
          pyinstaller --onefile --noconsole --name "EMS_Stream_Downloader" --collect-all customtkinter main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: EMS_Downloader_Exe
          path: dist/EMS_Stream_Downloader.exe
